/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP PC
 */
public class Calculation extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;
    /**
     * Creates new form Calculation
     */
    public Calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextdisplay = new javax.swing.JTextField();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn10 = new javax.swing.JButton();
        jBtn11 = new javax.swing.JButton();
        jBtn12 = new javax.swing.JButton();
        jBtn13 = new javax.swing.JButton();
        jBtn14 = new javax.swing.JButton();
        jBtn15 = new javax.swing.JButton();
        jBtn16 = new javax.swing.JButton();
        jBtn17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextdisplay.setEditable(false);
        jTextdisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jBtn1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn1MouseClicked(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn2.setText("3");
        jBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn2MouseClicked(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn3.setText("2");
        jBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn3MouseClicked(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn4MouseClicked(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn5MouseClicked(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn7MouseClicked(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn8.setText("+");
        jBtn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn8MouseClicked(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn9.setText("0");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn10.setText("9");
        jBtn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn10MouseClicked(evt);
            }
        });

        jBtn11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn11.setText("-");
        jBtn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn11MouseClicked(evt);
            }
        });

        jBtn12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn12.setText("8");
        jBtn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn12MouseClicked(evt);
            }
        });
        jBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn12ActionPerformed(evt);
            }
        });

        jBtn13.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn13.setText(".");
        jBtn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn13MouseClicked(evt);
            }
        });

        jBtn14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn14.setText("*");
        jBtn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn14MouseClicked(evt);
            }
        });

        jBtn15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn15.setText("/");
        jBtn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn15MouseClicked(evt);
            }
        });

        jBtn16.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn16.setText("=");
        jBtn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn16MouseClicked(evt);
            }
        });

        jBtn17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBtn17.setText("CLR");
        jBtn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextdisplay)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jBtn1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBtn2)
                                    .addGap(10, 10, 10)
                                    .addComponent(jBtn4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn7)
                                .addGap(10, 10, 10)
                                .addComponent(jBtn8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtn13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtn9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jBtn14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtn16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtn11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBtn17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1)
                    .addComponent(jBtn2)
                    .addComponent(jBtn3)
                    .addComponent(jBtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn5)
                    .addComponent(jBtn7)
                    .addComponent(jBtn6)
                    .addComponent(jBtn8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn12)
                    .addComponent(jBtn9)
                    .addComponent(jBtn10)
                    .addComponent(jBtn11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn13)
                    .addComponent(jBtn15)
                    .addComponent(jBtn14)
                    .addComponent(jBtn16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtn17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn12ActionPerformed

    private void jBtn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn17ActionPerformed
        jTextdisplay.setText("");
    }//GEN-LAST:event_jBtn17ActionPerformed

    private void jBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn1MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn1.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn1MouseClicked

    private void jBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn3MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn3.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn3MouseClicked

    private void jBtn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn2MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn2.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn2MouseClicked

    private void jBtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn4MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn4.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn4MouseClicked

    private void jBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn5MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn5.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn5MouseClicked

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String numone;
        numone = jTextdisplay.getText() + jBtn6.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn7MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn7.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn7MouseClicked

    private void jBtn12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn12MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn12.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn12MouseClicked

    private void jBtn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn10MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn10.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn10MouseClicked

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String numone;
        numone = jTextdisplay.getText() + jBtn9.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn8MouseClicked
        firstnum = Double.parseDouble(jTextdisplay.getText());
        jTextdisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jBtn8MouseClicked

    private void jBtn11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn11MouseClicked
        firstnum = Double.parseDouble(jTextdisplay.getText());
        jTextdisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jBtn11MouseClicked

    private void jBtn14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn14MouseClicked
        firstnum = Double.parseDouble(jTextdisplay.getText());
        jTextdisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jBtn14MouseClicked

    private void jBtn15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn15MouseClicked
        firstnum = Double.parseDouble(jTextdisplay.getText());
        jTextdisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jBtn15MouseClicked

    private void jBtn13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn13MouseClicked
        String numone;
        numone = jTextdisplay.getText() + jBtn13.getText();
        jTextdisplay.setText(numone);
    }//GEN-LAST:event_jBtn13MouseClicked

    private void jBtn16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn16MouseClicked
        String answer;
        secondnum = Double.parseDouble(jTextdisplay.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answer = String.format("%.0f", result);
            jTextdisplay.setText(answer);            
        }
        else if(operations == "-"){
            result = firstnum - secondnum;
            answer = String.format("%.0f", result);
            jTextdisplay.setText(answer);            
        }
        else if(operations == "*"){
            result = firstnum * secondnum;
            answer = String.format("%.0f", result);
            jTextdisplay.setText(answer);            
        }
        else if(operations == "/"){
            result = firstnum / secondnum;
            answer = String.format("%.0f", result);
            jTextdisplay.setText(answer);            
        }
    }//GEN-LAST:event_jBtn16MouseClicked

    /**
        * @param args the command line arguments
        */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn10;
    private javax.swing.JButton jBtn11;
    private javax.swing.JButton jBtn12;
    private javax.swing.JButton jBtn13;
    private javax.swing.JButton jBtn14;
    private javax.swing.JButton jBtn15;
    private javax.swing.JButton jBtn16;
    private javax.swing.JButton jBtn17;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextdisplay;
    // End of variables declaration//GEN-END:variables
}
